name: .NET Core

on: [push, pull_request]
jobs:
  build:

    name: Github Actions Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Build Reason
      run: echo ${{github.ref}} and ${{github.event_name}}
    - name: Build with dotnet
      run: dotnet build --configuration Release --nologo
    - name: Run tests
      run: dotnet test --configuration Release --no-build --nologo
    - name: Nuget pack
      run: ./scripts/deploy.sh ./src/Serilog.Sinks.Loki/Serilog.Sinks.Loki.csproj
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
